version: "3"

services:
    nginx:
        image: nginx:1.17.6-alpine
        container_name: nginx
        volumes:
            - "./proxy/default.conf:/etc/nginx/conf.d/default.conf" #bind container volumes with my host
            - "./proxy/httpscertificate:/etc/httpd/httpscertificate/" #bind container volumes with my host
        networks:
            - socket-net
        ports:
            - "80"
            - "8080"
            - "443:443"
    node1:
        image: cryssantos9/socker-app-img:v1
        container_name: node1
        environment:
            NODE_ENV: dev
            # DEBUG: '*'
            PORT: 8080
            MONGO_STRING: "mongodb://mongodb/chat-socketio"
        command: node_modules/.bin/nodemon --exec npm run dev
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules #data voluem ctn --> host
        networks:
            - socket-net
        ports:
            - "8080"
            - "27017"
        tty: true
        depends_on:
            - mongodb
            - nginx
    node2:
        image: cryssantos9/socker-app-img:v1
        container_name: node2
        environment:
            NODE_ENV: dev
            # DEBUG: '*'
            PORT: 8080
            MONGO_STRING: "mongodb://mongodb/chat-socketio"
        command: node_modules/.bin/nodemon --exec npm run dev
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        networks:
            - socket-net
        ports:
            - "8080"
            - "27017"
        tty: true
        depends_on:
            - mongodb
            - nginx
    mongodb:
        image: mongo
        container_name: ctn-mongo-socket-app
        ports:
            - "27017"
        networks:
            - socket-net

networks:
    socket-net:
        external: true
