#!/bin/bash
openssl req -sha256 -utf8 -newkey rsa:2048 -nodes -keyout ./httpscertificate/chatio.key -out ./httpscertificate/chatio.csr -config ./cnfFile/config.cnf

sleep 1

openssl x509 -req -in ./httpscertificate/chatio.csr -days 365  -signkey ./httpscertificate/chatio.key -out ./httpscertificate/chatio.crt -extensions req_cert_extensions -extfile  ./cnfFile/config.cnf && openssl x509  -in ./httpscertificate/chatio.crt -text 



