version: '3'
 
services:
    nginx:
        image: nginx:1.17.6-alpine
        container_name: nginx
        volumes:
            - "./default.conf:/etc/nginx/conf.d/default.conf" #bind container volumes with my host
            - "./httpscertificate:/etc/httpd/httpscertificate/" #bind container volumes with my host
        ports:
           - "80"
           - "443:443"